src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description_courte = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description_longue = null;

    #[ORM\Column(length: 255)]
    private ?string $categorie = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_creation = null;

    #[ORM\Column]
    private ?int $ordre = null;

    #[ORM\Column]
    private ?bool $visible = null;

    #[ORM\OneToMany(mappedBy: 'article', targetEntity: Images::class)]
    private Collection $images;

    public function __construct()
    {
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescriptionCourte(): ?string
    {
        return $this->description_courte;
    }

    public function setDescriptionCourte(string $description_courte): self
    {
        $this->description_courte = $description_courte;

        return $this;
    }

    public function getDescriptionLongue(): ?string
    {
        return $this->description_longue;
    }

    public function setDescriptionLongue(string $description_longue): self
    {
        $this->description_longue = $description_longue;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->categorie;
    }

    public function setCategorie(string $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getOrdre(): ?int
    {
        return $this->ordre;
    }

    public function setOrdre(int $ordre): self
    {
        $this->ordre = $ordre;

        return $this;
    }

    public function isVisible(): ?bool
    {
        return $this->visible;
    }

    public function setVisible(bool $visible): self
    {
        $this->visible = $visible;

        return $this;
    }

    /**
     * @return Collection<int, Images>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setArticle($this);
        }

        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getArticle() === $this) {
                $image->setArticle(null);
            }
        }

        return $this;
    }
    
    public function __toString(): string
    {
        return $this->getTitre();
    }

}

src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReservationRepository::class)]
class Reservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $lieu = null;

    #[ORM\Column]
    private ?int $place_restante = null;

    #[ORM\Column(length: 255)]
    private ?string $contenu = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLieu(): ?string
    {
        return $this->lieu;
    }

    public function setLieu(string $lieu): self
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getPlaceRestante(): ?int
    {
        return $this->place_restante;
    }

    public function setPlaceRestante(int $place_restante): self
    {
        $this->place_restante = $place_restante;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Repository\ArticleRepository;
use App\Repository\CommentaireRepository;
use App\Repository\ImagesRepository;
use App\Repository\ReservationRepository;
use Doctrine\ORM\EntityManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends AbstractController
{
    #[Route('/', name: 'app_main')]
    public function index(ArticleRepository  $articleRepo, ReservationRepository $resaRepo, CommentaireRepository $commentRepo, ImagesRepository $imagesRepo): Response
    {
        $articles = $articleRepo->findAll();
        $reservations = $resaRepo->findAll();
        $commentaires = $commentRepo->findAll();
        $sliders = $imagesRepo->findAll();
        // $slider = $imagesRepo->findBy(["id" => 1]);
        // dd($sliders);
        
        
        return $this->render('main/index.html.twig', [
            'articles' =>$articles,
            'reservations' =>$reservations,
            'commentaires' =>$commentaires,
            'sliders' =>$sliders,
        ]);
    }
    
    #[Route('/sophrologie', name: 'app_sophrologie')]
    public function sophrologie(ArticleRepository  $articleRepo, ImagesRepository $imagesRepo): Response
    {
        $articles = $articleRepo->findAll();
        $sliders = $imagesRepo->findAll();
        return $this->render('main/sophrologie.html.twig', [
            'articles' =>$articles,
            'sliders' =>$sliders,
        ]);
    }
    
    #[Route('/hypnose', name: 'app_hypnose')]
    public function hypnose(ArticleRepository  $articleRepo, ImagesRepository $imagesRepo): Response
    {
        $articles = $articleRepo->findAll();
        $sliders = $imagesRepo->findAll();
        return $this->render('main/hypnose.html.twig', [
            'articles' =>$articles,
            'sliders' =>$sliders,
        ]);
    }

    #[Route("/article/{id}", name:"show_article")]
    public function show($id, ArticleRepository $repo)
    {
        $article = $repo->find($id);

        return $this->render("main/article.html.twig", [
            "id" => $article->getId(),
            "article" => $article,
        ]);
    }

    #[Route("/mentions-légales", name:"mentionsLegales")]
    public function mentions(): Response
    {
        return $this->render ('main/mentionsLegales.html.twig');
    }

    #[Route("/politique-de-confidentialité", name:"politiqueDeConfidentialite")]
    public function politiqueDeConfidentialite(): Response
    {
        return $this->render ('main/politiqueDeConfidentialite.html.twig');
    }

    #[Route("/qui-suis-Je", name:"app_quiSuisJe")]
    public function quiSuisJe(): Response
    {
        return $this->render ('main/quiSuisJe.html.twig');
    }
}

templates/main/acopier.html.twig
{% extends 'base.html.twig' %}

{% block title %}Stéphanie de Vregille | Categorie
{% endblock %}

{% block body %}
	<div class="container">
    
    
    </div>
{% endblock %}

templates/main/article.html.twig
{% extends 'base.html.twig' %}

{% block title %}Stéphanie de Vregille | Categorie
{% endblock %}

{% block body %}
	<div class="container">
        <section class=" row article">
    
    
        
   
        
        <article class="col-md-9 mx-auto text-center border border-dark mb-3 p-3 mt-3 mr-1">
            <h2>{{article.titre}}</h2>
            <div class="metadata">Ecrit le {{article.dateCreation|date('d/m/Y à H:i:s')}} dans la catégorie {{ article.categorie }}</div>
            <div class="content">
                <img class="img-fluid" src="../uploads/images/{{article.images.0}}" alt="">
                <div class="text-center">{{ article.descriptionLongue|raw}}</div>
                
            </div>
        
        </article>
 
    </section>

    
    </div>
{% endblock %}

templates/main/hypnose.html.twig
{% extends 'base.html.twig' %}

{% block title %}Stéphanie de Vregille | Categorie
{% endblock %}

{% block body %}
	<div class="container my-3">
    <h1 class="m-5">L'hypnose Ericksonienne</h1>
    <h6 class="text-italic m-2">Qu'est-ce que c'est?</h6>
    <p class="justify">
    L'hypnose éricksonienne fait partie des thérapies brèves. C'est Milton Erickson, psychiatre et psychothérapeute américain, qui a modélisé cette méthode dans les années 1950. Il  s'agit de techniques de communication douces dites "permissives" qui permettent au praticien de s'adresser directement à l'inconscient de la personne, elle-même en état de profonde relaxation.
    <br>
    <strong>L'hypnose éricksonienne permet de contourner nos barrières mentales pour aller chercher les ressources dont nous avons besoin dans notre inconscient.</strong> C'est pour cette raison que la méthode peut parfois sembler "magique": les effets sont rapides et semblent être atteints sans efforts, tout simplement parce que le changement se fait à un niveau profond... 
    <br>
    L'hypnose existe depuis des siècles, et sous différentes formes: en France, cette technique retrouve aujourd'hui ses lettres de noblesse grâce à son efficacité. De nombreuses personnes arrêtent de fumer, retrouvent un sommeil de qualité, apaisent leurs relations conjugales ou parentales, sortent de phobies ou apaisent des traumas, et ceci en une à cinq séances. 
    </p>
    <p class="justify">
    L'hypnose éricksonienne est une thérapie brève qui convient pour de nombreux objectifs, à tous et à tous âges, avec très peu de contre-indications. Contrairement à l'hypnose de spectacle où l'hypnotisé ne maîtrise pas ce qui lui arrive et pour laquelle seulement 15 à 30% des personnes sont réceptives, l'hypnose éricksonienne vous laisse le contrôle de la situation: je vous tends les clés pour que vous puissiez avancer.
    </p>
    <div class="row">
    {% for article in articles %}
        {% if article.categorie == 'Hypnose' %}
        {% if article.visible == 1 %}
        <div class="col-lg-6 col-sm-12">
            <h2 class="my-2 text-center">{{article.titre}}</h2>
            <img src="../uploads/images/{{article.images.0}}" alt="photo article {{article.categorie}}" class="img-fluid">
            <p class="justify">{{article.descriptionLongue|raw}}</p>
        </div>
        {% endif %}
        {% endif %}
        
    {% endfor %}
    </div>

    </div>
{% endblock %}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Stéphanie de Vregille
{% endblock %}

{% block body %}
	<div id="carouselExampleCaptions" class="carousel slide carousel-fade" data-bs-ride="carousel">
		<div class="carousel-indicators">
		{% for slider in sliders|sort((a, b) => a.ordre <=> b.ordre) %}
			{% if slider.sliders != 0%}
			{% set slideTo = slider.ordre - 1 %}	
				<button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="{{slideTo}}" {% if slider.ordre == 1 %} class="active" {% endif %} aria-current="true" aria-label="Slide {{slider.ordre}}"></button>
			{% endif %}			
		{% endfor %}
		</div>
		<div class="carousel-inner" data-bs-interval='3500'>
			{% for slider in sliders|sort((a, b) => a.ordre <=> b.ordre) %}
				{% if slider.sliders != 0 %}
					<div class="carousel-item {% if slider.ordre == 1 %} active {% endif %}">
						<img src="../uploads/images/{{slider.image}}" class="d-block w-100" alt="photo Stephanie de Vregille" style="height:75vh; object-fit:cover;">
						<div class="carousel-caption d-none d-md-block">
							<a href="#" class="btn btn-custom">Stéphanie de Vregille | découvrez mes spécialités</a>
						</div>
					</div>
				{% endif %}
			{% endfor %}
		</div>
		<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
			<span class="carousel-control-prev-icon" aria-hidden="true"></span>
			<span class="visually-hidden">Précédent</span>
		</button>
		<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
			<span class="carousel-control-next-icon" aria-hidden="true"></span>
			<span class="visually-hidden">Suivant</span>
		</button>
	</div>

	<div class="container p-4">
		{% for article in articles %}
			{% if article.visible == 1  %}
				{% if article.ordre is odd%}
					<div class="d-flex align-items-center justify-content-around mb-3">
						<div class="flex-shrink-0 w-50 img">
							<img src="../uploads/images/{{article.images.0}}" alt="photo article {{article.categorie}}" class="img-fluid">
						</div>
						<div class=" ms-3">
							<h5>{{article.titre}}</h5>
							<p>{{article.descriptionCourte|raw}}</p>
							<a href="{{path("show_article",{id:article.id})}}" class="btn btn-custom">plus d'informations</a>
						</div>
					</div>
					<hr>
				{% else %}
					<div class="d-flex align-items-center justify-content-around mb-3">
						<div class="ms-3">
							<h5>{{article.titre}}</h5>
							<p>{{article.descriptionCourte|raw}}</p>
							<a href="{{path("show_article",{id:article.id})}}" class="btn btn-custom">plus d'informations</a>
						</div>
						<div class="flex-shrink-0 w-50 img">
							<img src="../uploads/images/{{article.images.0}}" alt="la belle photo" class="img-fluid">
						</div>
					</div>
					<hr>
				{% endif %}
			{% endif %}
		{% endfor %}
	</div>
	<div class="container-fluid bg-custom text-center text-white">
		<h2>Inscriptions pour les cours collectifs de sophrologie à la MJC de Quincieux:</h2>
		
		{% for reservation in reservations %}
			{% if reservation.placeRestante == 0 %}
				<p>Le cours ayant lieu {{ reservation.contenu }} est complet.</p>
			{% else %}
				<p>Il reste {{ reservation.placeRestante }} place{% if reservation.placeRestante > 1 %}s{% endif %} pour le cours ayant lieu {{ reservation.contenu }}.</p>
			{% endif %}
		{% endfor %}
		<h2>Contactez-moi si vous êtes intéressé !</h2>
	{# </div>
	<div class="container-fluid bg-custom my-0"> #}
		<div class=" lg-col-8 pt-4 mb-8 ">
			<h1 class="font-serif mb-3">Stephanie de Vregille</h1>
			<p class="text-lg">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat at aut magnam quis reiciendis? Nobis facere, nisi dignissimos sed illo veniam quo odio repellendus corrupti odit labore at ipsum blanditiis harum id eaque doloribus iure non. Ducimus aliquid quaerat esse nostrum soluta, excepturi minus aut illo harum, rerum repudiandae qui.</p>
		</div>
		<div class="d-flex flex-col md:flex-row items-center justify-content-around mb-4 ">
			<div class="text-sm d-flex flex-row items-center w-full">
				<span aria-hidden="true" class="fas fa-location p-3" title="Location" alt="">
					<i class="fas fa-hotel"></i>
				</span>
				<span class="sr-only">Lieu:</span>
				<div>
					Stéphanie de Vregille<br>
					44 D306, 69380 Les Chères<br>
					5 Rue de la Poste, 69380 Les Chères
				</div>
			</div>
			<div class="row">
			<div class="text-sm d-flex flex-row items-center w-full">
				<i class="fas fa-phone"></i>
				<span aria-hidden="true" class="dc-icon dc-call p-3" title="Call" alt=""></span>
				<span class="sr-only">Téléphone:</span>
				<div>
					06 14 39 14 69
				</div>
			</div>
			<div class="text-sm d-flex flex-row items-center w-full">
				<i class="fas fa-envelope"></i>
				<span aria-hidden="true" class="dc-icon dc-call p-3" title="Call" alt=""></span>
				<span class="sr-only">Téléphone:</span>
				<div>
					stephanie.hypnosophro@gmail.com
				</div>
			</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/main/mentionsLegales.html.twig
{% extends 'base.html.twig' %}

{% block title %}Stéphanie de Vregille | Categorie
{% endblock %}

{% block body %}
	<div class="container mentions">
    <h1>Mentions Légales</h1>
        <div>
            <p>
            Ce site appartient à Stéphanie de Vregille domiciliée au<br>
            <i class="fas fa-home me-3"></i>44 D306<br>
            69380 Les Chères
            </p>
        </div>
        <p>
        SIRET : 879698082 00010
        </p>
        <div>
            <p>
                <i class="fas fa-envelope me-3"></i>
                stephanie.hypnosophro@gmail.com
            </p>
            <p>
                <i class="fas fa-phone me-3"></i>
                06 14 39 14 69
            </p>
        </div>


    
    </div>
{% endblock %}

templates/main/politiqueDeConfidentialite.html.twig
{% extends 'base.html.twig' %}

{% block title %}Stéphanie de Vregille | Categorie
{% endblock %}

{% block body %}
	<div class="container mentions">
    <h1>Politique de Confidentialité</h1>
    <h4>Avis important sur le traitement des données en relation avec Google Analytics</h4>
    
    </div>
{% endblock %}

templates/main/quiSuisJe.html.twig
{% extends 'base.html.twig' %}

{% block title %}Stéphanie de Vregille | Categorie
{% endblock %}

{% block body %}
	<div class="container py-5">
		<h1>Qui je suis</h1>
		<p>
			J'ai commencé ma carrière professionnelle dans la petite enfance en tant qu'éducatrice de jeunes enfants, puis directrice de crèche, puis responsable de relais assistantes maternelles. Dans ces postes, j'ai pu accompagner des enfants au quotidien, soutenir les parents et former les équipes de professionnels. Je me suis d'abord  formée à des outils de coaching et de management, puis à la communication non-violente, le yoga pour enfants, et le soutien à la parentalité.
		</p>
        <p>
        Lorsque j'ai découvert l'hypnose éricksonienne, c'est un nouveau sens qu'a pris ma carrière : <strong>cet outil puissant permet en effet de débloquer des situations et d'obtenir en peu de temps des résultats très marquants</strong>.
        </p>

        <p>
        En parallèle, j'ai suivi une formation de <strong>sophrologue</strong> longue, sérieuse et complète, avec des spécialisations pour l'<strong>accompagnement des enfants</strong> et sur la <strong>gestion du stress (tous âges)</strong>. Cette méthode tournée vers la conscience de soi apporte encore d'autres réponses en passant par <strong>la respiration et le corps</strong>.
        </p>
        <p>
        Je vous accompagne aujourd'hui à tout âge selon vos besoins et votre sensibilité
        <br>
        La sophrologie et l'hypnose sont deux outils très complémentaires, et donnent une <strong>approche globale encore plus efficace</strong>.
        </p>
        <p>
        J'interviens aussi en entreprise et associations pour des ateliers à thèmes ainsi qu'en MJC pour des cours collectifs hebdomadaires. J'adhère au code de déontologie de la SSI, je continue à me former chaque année et je fais partie d'un groupe de supervision, une démarche supplémentaire pour des accompagnements de qualité. 
        </p>
        <br>
        <br>
        <p>
        <strong>Mon petit plus</strong> : mon travail sur le stress et ses effets ainsi que sur les émotions.
        </p>
        <br>
        <p>
        Mon message : <strong>faites-vous confiance, vous avez en vous toutes les ressources dont vous avez besoin!</strong>
        </p>
	</div>
{% endblock %}

templates/main/sophrologie.html.twig
{% extends 'base.html.twig' %}

{% block title %}Stéphanie de Vregille | Categorie
{% endblock %}

{% block body %}
	<div class="container">
    
    
    </div>
{% endblock %}